import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CardWrapper from "@/components/CardWrapper/CardWrapper";
import { useState } from "react";
import AddRecipe from "@/components/AddRecipe/AddRecipe";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <AddRecipe />
        <CardWrapper />
      </div>
    </>
  );
}
